// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function GetLastUpdateCheck() {
  return window['go']['main']['App']['GetLastUpdateCheck']();
}

export function GetStartURL() {
  return window['go']['main']['App']['GetStartURL']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function OpenAnyFileDialog() {
  return window['go']['main']['App']['OpenAnyFileDialog']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenUpdateDownload() {
  return window['go']['main']['App']['OpenUpdateDownload']();
}
