// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {system} from '../models';

export function CheckForUpdate():Promise<updater.UpdateState>;

export function GetLastUpdateCheck():Promise<updater.UpdateState>;

export function GetStartURL():Promise<string>;

export function GetSystemInfo():Promise<system.SystemInfo>;

export function OpenAnyFileDialog():Promise<string>;

export function OpenDataDir():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenUpdateDownload():Promise<void>;
